os:
- linux
- osx
sudo: required
dist: trusty
osx_image: xcode9.4.1
services:
- docker
script:
- make test
after_success:
- bash <(curl -s https://codecov.io/bash)
install:
- eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
before_deploy:
- make release-and-deploy
deploy:
  provider: releases
  api_key:
    secure: j7oAjY6NB2ENoYQJL2y6wTOazpFraVpAKH+sdAp+eM+OI4XNNuahZCNlXngDztGgUKrii1hH76LI5dBzMdKv+iCSefS3UPDStGT4V+K8JbWAb8ZCaJr33wMJCSFYtEqEisOBr43LOiqPk87zLXdl7gDtOgJj68CyI2bYAdxMBgCal40SFETnuV1i6Egy1LNJ9KRzpIMu+163eALHzfdREO0mpnLVOu7wkDuyCUzsjp1JO1OD8GYYlExa9qF15Za8qaMA1RbpQotbREp/eTC5ekbnaZHfXV3tUC7z7u1IKMNPQI9yNM4auzNNFU+bHRFq3U9JLYB6FOb3hA73MaeGf2II70pVukbrFEkaarDWeLD1uXXvWt1YUJVTHNMjoUnsPQeNc2krdwXtPGxPOQXnikURtnC/LduEksRvzxEUpDGSschlDRjK1RLnQcU3dampRNXzOLL52HWcg3ArKq808gOPkTqcCDvznM6FvaTpZs2A2cT3tXXQAZs/Dvk5Q2I/K+hCaOq8BjSibtiM/u1BFN1b27IfeUovKZGVR4tZutjI+mET43Qw08gP9yCljtxAju9PSaUJomi9KCZuiedd3Mh/Qhtq6ZjDrUgfYEI/ibuSKo3K9spyF3mevhjyhZ8//ysc+FgdfLbnX7wmm3yCu3FBntqvl1BRz4+6d24HfHo=
  file: release/*/*.bz2
  skip_cleanup: true
  on:
    tags: true
    repo: getGuaka/guaka-cli
